# Generated by Django 5.1 on 2024-08-31 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_log',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('course_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subject_details',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_description', models.TextField()),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.course_details')),
            ],
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('qualification_details', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.subject_details')),
            ],
        ),
        migrations.CreateModel(
            name='enrolled_details',
            fields=[
                ('enrollmentid', models.AutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.course_details')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.student_details')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.subject_details')),
            ],
        ),
    ]
