# Generated by Django 5.1 on 2024-09-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_details',
            old_name='course_id',
            new_name='course',
        ),
    ]
