# Generated by Django 5.1 on 2024-09-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_rename_course_id_subject_details_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled_details',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='staff_details',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
