# Generated by Django 5.1 on 2024-09-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rename_subject_id_enrolled_details_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled_details',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrolled_details',
            old_name='student_id',
            new_name='student',
        ),
    ]
