# Generated by Django 5.1 on 2024-09-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_rename_course_id_enrolled_details_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_log',
            old_name='password',
            new_name='admin_password',
        ),
        migrations.RenameField(
            model_name='admin_log',
            old_name='username',
            new_name='admin_username',
        ),
    ]
