# Generated by Django 5.1 on 2024-09-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_rename_password_admin_log_admin_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_details',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject_details',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.staff_details'),
        ),
    ]
