# Generated by Django 5.1 on 2024-09-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_subject_details_subject_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_details',
            name='subject_fee',
            field=models.BigIntegerField(),
        ),
    ]
