# Generated by Django 5.1 on 2024-09-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_alter_subject_details_subject_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_details',
            name='description',
        ),
    ]
